### ISSUE TITLE
Ros_serial + Arduino Due configuration

### ISSUE THREAD

**Issue by tparmelee** [ros-drivers/rosserial#113]
I encountered an issue while using the Arduino Due with the library, I fixed it for my needs but it may have broken the library for other Arduinos.  The Due has the programming port and the Native port. The programming port is connected via UART and is accessed by Serial and I believe that the Native port is connected via USART and is accessed by Serial1.

Using the library as installed from the repo compiling in the IDE:

```
In file included from /home/tyler/Arduino/libraries/ros_lib/ros.h:39, from Blinktest.ino:6:
/home/tyler/Arduino/libraries/ros_lib/ArduinoHardware.h: In constructor 'ArduinoHardware::ArduinoHardware()':
/home/tyler/Arduino/libraries/ros_lib/ArduinoHardware.h:68: error: cannot convert 'USARTClass*' to 'UARTClass*' in assignment
```

If I switched the class include to 'USARTClass*' at line 48 in ArduinoHardware.h, then after uploading to the board and running the serial_node.py file this prints to the terminal:

```
Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino
```

My fix is in in ArduinoHardware.h, at line 48 leave it as 'UARTClass*' and at line 68 change 'Serial1' to 'Serial'. This allows serial communication via the programming port on the Due.

However I am fairly certain this change alone will break the library for another types of hardware (IE the Leonardo based on the commenting in the ArduinoHardware.h). ALso this only works for the programming port on the due, the native port will require different a serial setup.

Apologies if the above was gibberish or needed to be formatted differently, if you want me to clarify I can.

**Comment by mikepurvis** [comment]
Glad you were able to fix this. I agree that the business of specifying which serial port to use on Leonardo and Due is not at all obvious, and probably warrants a giant "THIS MIGHT BE YOUR ISSUE" warning on the rosserial wiki page.

**Comment by js376282** [comment]
Has this been resolved in the current version of the code?  I'm having a similar issue but even after reading through the current version of ArduinoHardware.h I  don't see how it can be resolved.

**Comment by NanoShaw** [comment]
In the latest version of the example code for Blink, I've tried this with ros-kinetic-rosserial-arduino and it works for a publisher node in Arduino Due. The only problem I have faced thus far is that the first packet is lost but the next packet published to the topic is carried onwards.

#define USE_USBCON     // Add this line before the #include <ros.h> line of code for Arduino Due
#include <ros.h>

@js376282 referred this solution in  #284 I will report back with the results of a subscriber node.

**Comment by NanoShaw** [comment]
I have tried using the Blink example it executes properly with the slight addition of the same
#define USE_USBCON before #include <ros.h>
The Arduino Due loses the connection for the first package and then works properly onwards. Toggling on user commands.

Also another thing I still observe, this runs only on the programming port of the Arduino Due. And the maximum baudrate I achieved is 115200 (perhaps due to the internal limitation of the atmega usb to serial connection).
