### ISSUE TITLE
Warning, failed to generate libraries for the following packages:   map_msgs

### ISSUE THREAD

**Issue by Kytatoo** [ros-drivers/rosserial#118]
During the installation and during this step "rosrun rosserial_arduino make_libraries.py ." , I got the following error :
 **\* Warning, failed to generate libraries for the following packages: ***
    map_msgs

I tried to manually setup map_msgs package with git clone https://github.com/ethz-asl/map_msgs.git but it does not resolve the issue.

How can I resolve this issue ?

**Comment by mikepurvis** [comment]
Do you specifically need map_msgs? If not, you can ignore the warning—all other messages will have been generated and be usable.

**Comment by Kytatoo** [comment]
Thanks to answer to my question. Yes I would like to use map_msgs  (sensor_msgs, laser_scan). Is it a known issue ?

**Comment by mikeferguson** [comment]
There are a very few certain message packages that fail that we never figured out why -- map_msgs is one of them.

**Comment by Kytatoo** [comment]
Ok thanks, good to know it. 
I will try to create a "custom message" and convert it to map_msgs later.

**Comment by mikepurvis** [comment]
If you end up debugging it and figuring what's going wrong, please open a new ticket— in theory, the rosserial client lib generator should support all message configurations, so it'd be great to know what's up with those problematic ones.

**Comment by cjsut** [comment]
Figured this out -- writing the ticket now.

**Comment by AkshayaRaj** [comment]
Same problem here . But I have a package with custom messages which fails as well. Does it have anything to do with the fact that some custom messages definitions include other custom messages ?

**Comment by mikepurvis** [comment]
The issue is service definitions which don't specify a response. The fix is part of this review:

https://github.com/ros-drivers/rosserial/pull/149/files#diff-cdb1393b648e99cc30d77de2152e8146R435
