### ISSUE TITLE
SoftSerial on Arduino buffer size corruption

### ISSUE THREAD

**Issue by ibaranov-cp** [ros-drivers/rosserial#121]
I have an Arduino hooked up with rosserial, that is also talking to other serial devices on a softserial port.

So default buffer size for SoftSerial is 64 bytes. However, my message is longer than that, so I set it to 100 bytes. This is changed in SoftSerial.h within the default Arduino libraries.

Everything looks ok, but now the 100 bytes returned are garbage.
Interestingly, a sketch without ROS, just pure arduino softserial, with this modification, works fine.

What in the Rosserial_arduino code could be causing this? I have been looking for a hardcoded 64 byte register somewhere, but haven't found it yet... Is this a RAM issue?

**Comment by mikepurvis** [comment]
Hi @ibaranov-cp,

I have no particular experience with SoftSerial— looking at [the source](https://github.com/arduino/Arduino/blob/master/libraries/SoftwareSerial/SoftwareSerial.h#L66), it appears that the receive buffer is a statically-allocated char array. I'm assuming you copied the `SoftwareSerial.h/cpp` files into your source folder and then modified _SS_MAX_RX_BUFF? I don't actually know how linking multiple sources works with the Arduino IDE.

One thing I've found with the 32-bit ARM chips is that statically-allocating the NodeHandle structure can be a bit hit and miss. Can you try allocating as much as possible on the stack (ie, inside of `main`), and see if that improves things?
