### ISSUE TITLE
rosserial_arduino Hello World file won't verify

### ISSUE THREAD

**Issue by mattc1** [ros-drivers/rosserial#127]
Edit: Solved

I've been using this tutorial to get everything set up: (http://wiki.ros.org/rosserial_arduino/Tutorials/Arduino%20IDE%20Setup) I can install everything without an issue I think, the ros_lib folder is places in my sketchbook libraries. But when I do the next tutorial with the helloworld example, the code does not verify correctly. When I try to verify with the checkmark in the Arduino IDE, I get the following set of error codes:

In file included from /home/user/sketchbook/libraries/ros_lib/ros.h:38:0,
                 from HelloWorld.cpp:6:
/home/user/sketchbook/libraries/ros_lib/ros/node_handle.h: In member function 'virtual int ros::NodeHandle_<Hardware, MAX_SUBSCRIBERS, MAX_PUBLISHERS, INPUT_SIZE, OUTPUT_SIZE>::spinOnce()':
/home/user/sketchbook/libraries/ros_lib/ros/node_handle.h:260:45: error: expected unqualified-id before numeric constant
/home/user/sketchbook/libraries/ros_lib/ros/node_handle.h:260:45: error: expected ')' before numeric constant

I've reinstalled the ros_lib as well as rosserial and I keep getting this error, so I don't know what the problem is. I looked around line 260 of the node_handle.h file but I didn't notice anything out of place.

**Comment by bbsan2k** [comment]
I'm currently experiencing the same issues. Is there any fix?

**Comment by mattc1** [comment]
SOLUTION:

I'm running Arduino 1.0.5

I fixed the problem by changing /Sketchbook/library/ros_lib/ros/node_handle.h line 260 from
}else if (topic_ == TopicInfo::ID_TX_STOP){ 
to
}else if (topic_ == ID_TX_STOP){

However, this gave me a new error message:

/usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp: In member function 'size_t Print::print(const __FlashStringHelper*)':
/usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp:44:9: error: 'prog_char' does not name a type
/usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp:47:23: error: 'p' was not declared in this scope

So to fix this I edited usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp, line 44 from
const prog_char *p = (const prog_char *)ifsh;
to
const char PROGMEM *p = (const char PROGMEM *)ifsh;

Now it compiles!

**Comment by RbSCR** [comment]
I experienced the same error.

I solved it by removing/commenting in node_handle.h the line 

```
#define ID_TX_STOP 11  //hardcode for hydro version
```

now it compiles without any other errors.

**Comment by mikepurvis** [comment]
Fixed via f3bc2b541607418b7bad6e43fbdbf68c27daca51
