### ISSUE TITLE
rosserial_client does not handle a disconnection from the server elgantly

### ISSUE THREAD

**Issue by jscatena88** [ros-drivers/rosserial#128]
When the server goes down (e.g for a restart etc) the rosserial client will just get stuck in the spinOnce() state machine's while(true) loop with mode_ = MODE_FIRST_FF (i.e. 0). For the use case of a potentially remote system it would be nice to be able to respond gracefully to the server coming up and down while the remote machine stays on. 

I fixed it in our code base by changing(@ line 209 in node_handle.h):

```
    }else if( mode_ == MODE_FIRST_FF ){
        if(data == 0xff){
          mode_++;
          last_msg_timeout_time = c_time + MSG_TIMEOUT;
        }
```

to: 

```
    }else if( mode_ == MODE_FIRST_FF ){
        if(data == 0xff){
          mode_++;
          last_msg_timeout_time = c_time + MSG_TIMEOUT;
        }
        else if (difftime(hardware_.time(), c_time) > (SYNC_SECONDS)){
          //Been here too long, return -1
          return -1;
    }
```

With that code in place my code looks for the -1 to be returned by spinOnce() and exits if it is seen.

If this fix seems generally applicable feel free to add it, or I can commit it.

**Comment by jscatena88** [comment]
I actually have it return a -2 now so I can differentiate it from another return -1 in the statemachine

**Comment by mikepurvis** [comment]
I bring my server up and down all the time and have not been bitten by this, but it looks like a good change. Can you create a pull request against `indigo-devel` for review?

**Comment by jscatena88** [comment]
Sorry I haven't checked git hub in a few days. I should be able to do that this weekend

**Comment by jscatena88** [comment]
Just made the pull request. Barring any problems with the code I will close this issue once it is merged
