### ISSUE TITLE
Hello World on Mac OSX vs Ubuntu

### ISSUE THREAD

**Issue by Donny3000** [ros-drivers/rosserial#137]
Hello All,

I'm attempting to use rosserial on a DAGU T'REX Motor controller to receive statuses and send commands to it, but I wanted to become familiar with rosserial first. So, I began working through the tutorials for rosserial on my Ubuntu 14.04 VM (where my installation of ROS indigo resides), specifically the Publisher tutorial for my Arduino Mega 256. Everything worked beautifully and without a hitch. I was able to see the topic and subscribe to it and receive the published "hello world!" string. But, if work through the same tutorial on the Mac side (setting up the IDE by copying the ros_lib folder from the libraries folder on my VM to the libraries folder on my Mac and compiling/uploading the sketch), and then connect my arduino back to my Ubuntu VM, rosserial_python will never synch up to forward the topic to the ROS system.

Would anyone have a suggestion as to my this may be happening?

**Comment by Donny3000** [comment]
This was a configuration issue on my part. Closing this issue.

**Comment by mikeferguson** [comment]
If you think it is something someone else might bump into -- please post what you fixed, might help out a fellow user in the future.

**Comment by Donny3000** [comment]
Well, it looks like it wasn't a configuration issue after all.  If I compile/upload the Hello World example on my Mac Arduino IDE and then connect the arduino to my Ubuntu VM, I keep getting sync errors. Not the case if I compile/upload on my Ubuntu VM.  I'm not sure what the difference would be.

**Comment by Donny3000** [comment]
With further investigation, I've been able to get the Hello World example compiled/upload with the Mac OSX Arduino IDE to work by "kickstarting" the arduino so to speak.  If open up a serial terminal emulator and send the following data packet

```
0xff 0xfe 0x00 0x00 0xff 0x00 0x00 0xff
```

to query for topics, close the terminal session and then execute the rosserial_python serial_node command

```
rosrun rosserial_python serial_node.py _port:=/dev/ttyACM0
```

to begin receiving the published data, client and the arduino will synch and begin publishing.  If I don't, kicking things off by sending the query packet, then client and arduino will never synch.  I don't have send such a command prior to running the serial_node client on the Ubuntu side.

This doesn't make much sense why I would have to do this.  Any hints or suggestions as to where this discrepancy may be found?

**Comment by mikepurvis** [comment]
Out of curiosity, is the C++ [rosserial_server](http://wiki.ros.org/rosserial_server) serial node affected as well?

```
roslaunch rosserial_server serial.launch port:=/dev/ttyUSB0
```

**Comment by Donny3000** [comment]
Thanks Mike for that command.  That command works. Any idea why the C++ server would work over the python?

After further investigation by reading the documentation on rosserial_server, I ran this command:

```
rosrun rosserial_server serial_node
```

which works as well, but give the following warnings

```
$ rosrun rosserial_server serial_node 
[ INFO] [1409667742.543654278]: Opening serial port.
[ INFO] [1409667742.551483373]: Starting session.
[ INFO] [1409667742.552906964]: Attached client is using protocol VER2 (hydro)
[ WARN] [1409667743.553282169]: Sync with device lost.
[ WARN] [1409667743.959138509]: Rejecting message on topicId=125, length=17 with bad checksum.
[ INFO] [1409667743.976565534]: waitForService: Service [/message_info] has not been advertised, waiting...
[ WARN] [1409667748.996993859]: Timed out waiting for message_info service to become available.
[ WARN] [1409667748.998713454]: Failed to call message_info service. Proceeding without full message definition.
[ WARN] [1409667748.998872219]: Advertising on topic [/chatter] with an empty message definition.  Some tools (e.g. rosbag) may not work correctly.
```

So, seeing that this enables the code uploaded from my Mac Arduino IDE to work, I decided to test the same command (rosrun rosserial_server serial_node) with the code uploaded by my Ubuntu Arduino IDE and it gives the same results.

For clarity, a summary of my findings is as follows:

| ROS Serial Command | Ubuntu Compiled Code | Mac OSX Compile Code |
| --- | --- | --- |
| rosrun rosserial_python serial_node.py | synchs | does not synch |
| roslaunch rosserial_server serial.launch | synchs | synchs |
| rosrun rosserial_server serial_node | synchs (but without full message definition warning) | synchs (but without full message definition warning) |

I wouldn't think that the complier bundled with the Mac OSX Arduino IDE would generate different code than the Ubuntu Arduino IDE. I'm still not sure why the C++ implementation would work over the python for getting the Mac Arduino compiled code to work. So, I'm still left in a perplexed state.

**Comment by mikepurvis** [comment]
It's hard to say for certain, but this may be down to an issue in how your virtualization software handles the handoff of the USB device between OS X and the guest Ubuntu. It's possible that there's some quirk that's affecting how pyserial (inside `rosserial_python`) is able to pick up the connection. If you really want to dig into this further, you could do experiments like downloading the code from OS X, then completely disconnecting the device, and reconnecting it directly to the guest.

In general, `rosserial_server` is more aggressive about trying to recover a bad or broken connection— we built it at Clearpath to be the ROS MCU interface [for the Grizzly](http://www.clearpathrobotics.com/grizzly/), so we really wanted it performant and robust. If you don't have need of parameters or services, I suggest using `rosserial_server` for your project.

**Comment by Donny3000** [comment]
Thanks Mike for the detailed information.  I will try conducting a few more like you suggested to get a better understanding of whats going on. Specifically with a desktop PC just to be certain.  I'll report back my findings.

**Comment by Donny3000** [comment]
Mike,

I just ran the experiment that you suggested by downloading the code from OSX, completely removing the device and reconnecting to an Ubuntu PC rather than my VM.  Running all three commands I tried earlier resulted in successful syncing with the arduino.  So, it does appear to be a quirk within the Parallels Desktop Virtualization software that I'm running that you insinuated to earlier.

So, just a note to those who might run into a similar issue when developing Arduino code on OSX:

### Develop on OSX and run on ROS PC
1. Deploy code on OSX host
2. Disconnect device from OSX host
3. Connect to ROS PC and execute `rosrun rosserial_python serial_node.py port:=<serial_device>` node

Or, if you need to have a ROS VM, then

### Develop on OSX and run on ROS VM
1. Deploy code on OSX host
2. Disconnect device from OSX host
3. Connect device to ROS VM
4. _"Kickstart"_ the serial connection by manually sending a query packet using a serial terminal emulator.
   - ROS Serial Query Packet: `0xff 0xfe 0x00 0x00 0xff 0x00 0x00 0xff`
5. Now, Execute `rosrun rosserial_python serial_node.py port:=<serial_device>` node

**Comment by mikepurvis** [comment]
Cool, thanks for looking into it.
