### ISSUE TITLE
length limitation?

### ISSUE THREAD

**Issue by dvenable1** [ros-drivers/rosserial#141]
I am trying to use rosserial  windows to pass a laser scan to a windows box for further non-navigation related processing.  It appears that a LaserScan message is not passed by rosserial; if I truncate the range data to ~50 values it will send out the message, otherwise the message never leaves ros land.  I am guessing there is a buffer limitation on the message size since rosserial is heavily used for embedded applications, but I am communicating with a PC.  If there is a buffer limit, it there a way to change it?

Thanks,
/d

**Comment by mikepurvis** [comment]
Hi @dvenable1— there are two issues at work here. One is the overall message length limitation, the other is the array size limitation. There's presently a discussion about this going on in #130, in the context of passing pointclouds from Windows to ROS.

The short answer is: it's a protocol breakage, and we'd consider merging a patch for jade.

**Comment by mikepurvis** [comment]
Closing this to track it in #130.

**Comment by sevenbitbyte** [comment]
This maybe fixed in PR #222
