### ISSUE TITLE
make_libraries.py fails to generate rosserial_msgs and rosserial_arduino

### ISSUE THREAD

**Issue by Overv** [ros-drivers/rosserial#147]
Hi,

I've followed the tutorial in the ROS wiki to set up rosserial_arduino:

http://wiki.ros.org/rosserial_arduino/Tutorials/Arduino%20IDE%20Setup

Unfortunately `make_libraries.py` fails to generate libraries for `rosserial_msgs` and `rosserial_arduino`:

```
*** Warning, failed to generate libraries for the following packages: ***
    rosserial_msgs
    map_msgs
    rosserial_arduino
```

Is this a bug in the latest version or is there something I've done wrong? I'm running ROS indigo on Ubuntu 14.04.

**Comment by mikepurvis** [comment]
Hi @Overv!

Sorry for your trouble. Can you clarify whether you're using rosserial from a source workspace or installed from debian packages?

**Comment by Overv** [comment]
@mikepurvis I installed it from the debian packages.

**Comment by mikepurvis** [comment]
Hmm, it's definitely working for me.
- Please confirm that you have the most recent version of everything. Run `sudo apt-get dist-upgrade`.
- Please also confirm that you're not in a weird overlay situation. Immediately before running the generate_libraries.py command, re-run `source /opt/ros/indigo/setup.bash`.

**Comment by Overv** [comment]
Thank you, the `source /opt/ros/indigo/setup.bash` command fixed it. Still, I already have that in my bashrc. What could have messed it up?

**Comment by mikepurvis** [comment]
You're a victim of catkin's controversial automatic workspace chaining feature: https://github.com/ros/catkin/issues/232

There's not much you can really do to protect yourself, except that when faced with a weird build failure which doesn't otherwise make sense, check the value of your `CMAKE_PREFIX_PATH`, to see if the base and overlay workspaces have ended up reversed.

**Comment by RoboBil** [comment]
Good Morning Mike,

I also have had so much trouble with the rosserial install described here: http://answers.ros.org/question/202490/warning-failed-to-generate-libraries-for-the-following-packages-geometry_msgs-sensor_msgs-shape_msgs/

When I follow your instructions on this thread, the results are better but I still get the following error

**\* Warning, failed to generate libraries for the following packages: ***
    map_msgs

I'm a complete programming/ros beginner. Any suggestions would be appreciated.

RoboBill

**Comment by Mecb1407** [comment]
@mikepurvis thank you, buddy, I solved the problem with your help.
execute command `source /opt/ros/kinetic/setup.bash`
