### ISSUE TITLE
rosserial_arduino: cmake build hex file location

### ISSUE THREAD

**Issue by mitchellwills** [ros-drivers/rosserial#148]
When trying to follow CMake tutorial on the rosserial_arduino wiki I have a problem with uploading the hex file. When the hex file is built it is put in /devel/share/helloworld/. However when running the upload target avrdude gives the error: " error opening hello.hex: No such file or directory". Upon closer inspection before running the avrdude command cmake enters "/build/helloworld/firmware" which is not where the hex file is. I am building using "catkin_make helloworld_firmware_hello" and they attempting to upload with "catkin_make helloworld_firmware_hello-upload".

**Comment by mikepurvis** [comment]
Hi— I believe b5006a486b28b590802ad0e82d45c02cdc177c7f fixes this issue. If you're able to verify this from source locally then I'll cut a rosserial release.

Thanks for giving the CMake functionality a try, sorry for the hiccup!

**Comment by mitchellwills** [comment]
Yes I just tested it and it fixes the issue.

**Comment by mikepurvis** [comment]
Cool. Release coming: https://github.com/ros/rosdistro/pull/6217

Should be in shadow shortly and ros-public in a few weeks.
