### ISSUE TITLE
Wrong result of "deserialize" for negative valuse in Float64.h

### ISSUE THREAD

**Issue by AlexanderGershkovich** [ros-drivers/rosserial#150]
I've got a problem in Indigo using "geometry_msgs/Twist" messages for sending data to Arduino. The result of my short investigation is that "virtual int deserialize(unsigned char *inbuffer)" in "class Float64" (sketchbook/libraries/roslib/std_msgs/Float64.h) gives a wrong result for "this->data" if negative value was published to the topic. For the zero and positive values everything deserialzed correct, but for the negative values result is something like -1.24345983e-309 instead of -1.5.

**Comment by mikeferguson** [comment]
Are your sources up to date? Note https://github.com/ros-drivers/rosserial/pull/144 should have fixed this..

**Comment by AlexanderGershkovich** [comment]
You are rigth, it's my fault, the sources weren't up to date. Now it's fixed. Thank you very much!
