### ISSUE TITLE
catkin tools problem

### ISSUE THREAD

**Issue by niosus** [ros-drivers/rosserial#189]
Hello!

Thanks for all the effort, the package you implement is a real life saver! 

This may be not in priority, but for those of us who use catkin_tools and therefore the command `catkin build <some_pkg>` is not working properly as it cannot find the appropriate targets when using `rosserial_add_client_target`.

Following the tutorials [here](http://wiki.ros.org/rosserial_arduino/Tutorials/CMake) there is no way (as of now) to use `catkin build` instead of `catkin_make`. That would be great as I use the `catkin_tools` for all my projects and it is mutually incompatible with `catkin_make` way.

**Comment by niosus** [comment]
Oh, my bad, there was an error in rosserial_arduino tutorials and everything else is working just fine with catkin tools. Closing issue. Sorry for the noise.

**Comment by mikepurvis** [comment]
No sweat. Please consider fixing the tutorial, or at least posting what the issue was so that we can fix it. :)

**Comment by skohlbr** [comment]
I'd actually be interested, as I think I ran into this problem, too (catkin build no finding a target that catkin_make appears to find).
