### ISSUE TITLE
Problem in launching rosserial_python

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [ros-drivers/rosserial#213]
The rosrun to run the rosserial_python works after I have installed rosserial

```
rosrun rosserial_python serial_node.py
```

However, I cannot launch rosserial_python using roslaunch

```
<launch>

<node pkg="rosseiral" type="serial_node.py" name="serial_node">
    <param name = "port" value ="/dev/ttyACM0" />
    <param name = "baud" value = "115200" />
</node>



</launch>

```

How can I resolve the problem? Is the problem from the ROS_PACKAGE_PATH?

![screenshot from 2016-02-08 13 09 42](https://cloud.githubusercontent.com/assets/5248102/12878282/3f2d9bd2-ce65-11e5-902d-57e4511967ce.png)

**Comment by tonybaltovski** [comment]
Typo, should be rosserial not rosseiral.

**Comment by Jaeyoung-Lim** [comment]
@tonybaltovski  

Thanks for the help,

don't understand why I couldn't have found it...
