### ISSUE TITLE
rosserial_python issue while using serial_node. Classes from SerialClient.py not being imported

### ISSUE THREAD

**Issue by niteeshsood** [ros-drivers/rosserial#217]
Cannot use serial_node.py from the rosserial_python package.

I get the following message. 

from rosserial_python import SerialClient, RosSerialServer
ImportError: cannot import name RosSerialServer

For some reason the classes aren't being imported from SerialClient.py. I've solved the issue temporarily by adding SerialClient.py to the same folder as serial_node.py and using the following in serial_node.py

`from SerialClient import SerialClient, RosSerialServer`

Closed because I think I tried to build a package with the same name by mistake manually. I had tried uninstalling and then reinstalling rosserial package and the rosserial-arduino package for indigo but I was still having problems with it. Seems like a local issue caused by me. Apologies.

**Comment by raidhu** [comment]
did you find the solution. it helps me a lot I also have the same issue
