### ISSUE TITLE
ros kinetic

### ISSUE THREAD

**Issue by pavoldroba** [ros-drivers/rosserial#223]
Hi,

is there a plan to release this package for ROS Kinetic?

Thanks,
Pavol

**Comment by zaidpirwani** [comment]
Yeah, I would like to know as well, I just started with ROS, first installed kinetic, but then installed Jade cause I need to use rosserial.

Planning to make a robot with Arduino and Raspberry Pi and then have the bot communicate with other SAME bots over WiFi and BLE

**Comment by mikepurvis** [comment]
I need to do some smoke testing of the merged changes but then, yes, there will be a new release for Jade and Kinetic.

**Comment by robin-read** [comment]
Do you have an estimated release date for this at all?

**Comment by mikepurvis** [comment]
If you would be willing to build the current head on Kinetic and verify basic functionality (eg, Arduino publish/subscribe) with rosserial_server and rosserial_python, that would be very helpful.

**Comment by robin-read** [comment]
About to head off travelling for a week, so I'll have a quick look now, but realistically you'll have an answer in about a week and a half.

**Comment by vmatos** [comment]
I've just installed a fresh Xubuntu 16.04 + ROS kinetic.
Just built rosserial fine with no errors. Later today I'll update my arm toolchain for the new gcc arm PPA, and then I'll test rosserial_tivac + update tutorials.

Anything I should be looking out for?

**Comment by vmatos** [comment]
**1 -** I think I came across with something on `rosserial_client/cmake/rosserial_client-extras.cmake` that needs changing for kinetic: https://github.com/robosavvy/rosserial/issues/1

**2 -** The other issue I'm having, is a different behavior when building `rosserial_client` packages when messages are defined on the parent package. For instance my https://github.com/robosavvy/rosserial_tivac_tutorials package.

On Jade, I just make `catkin_make`, custom messages are generated first, are copied to `devel`, then `rosserial_client` uses them when generating `ros_lib` folder. Even if I have not sourced `devel/setup.bash`.

On Kinetic, on the first `catkin_make`,  custom messages are generated and copied to `devel`, but during `rosserial_tivac_tutorials_ros_lib`, on `make_library.MakeLibrary()`, the messages are not found by `roslib`.

```
md5sum = roslib.message.get_message_class(package+'/'+f[0:-4])._md5sum
```

returns None.

edit: I've been reporting my issue here: https://github.com/robosavvy/rosserial/issues/2

**Comment by robin-read** [comment]
So what I've just tested is cloning the latest rosserial repos and adding that to my Kinetic catkin workspace. `catkin_make` built without issue. I've connected my computer to an arduino (controlling the wheels of my robot) and have been able to publish Twist messages to the arduino, and receive back multiarray messages from the arduino with encoder tick counts.

Haven't tried making any custom messages for this, and everything has worked out of the box thus far. But I have only been using things that came in the box... :)

**Comment by khancyr** [comment]
Hi,
I use it on kinetic for some time. On arduino side, it seems ok. I didn't catch new problem.
Catkin build work fine too
But gcc6.1 trigger many errors...

**Comment by vmatos** [comment]
Has anyone tried to use `rosserial` capabilities using `rosserial_client`?
e.g. just like the tutorial for Arduino using cmake: http://wiki.ros.org/rosserial_arduino/Tutorials/CMake

I've just published a minimum example which reproduces my error. Can you try it?
https://github.com/vmatos/rosserial_ard_ws/

**Comment by mikepurvis** [comment]
Rosserial has been released to Kinetic.
