### ISSUE TITLE
Slow publishing Twist commands to arduino

### ISSUE THREAD

**Issue by h3ct0r** [ros-drivers/rosserial#224]
Hi,

I'm developing a Rosserial bridge with an arduino mega 256 to read information from an IMU and send commands to 2 servos. I'm setting the serial baud to 115200 to increase the speed.

The readings from the IMU are fast, but when I publish some Twist command the arduino stops sending the IMU messages and it takes at least 3-5 seconds to receive and process the servo command.

Even using this code it waits at least 4 seconds to execute the movement:

`$ rostopic pub -1 /cmd_vel geometry_msgs/Twist -- '[2.0, 0.0, 0.0]' '[0.0, 0.0, 1.8]'`

Is this a normal behaviour? How can I make the Arduino to process the Twist messages faster?

The code i'm using is on: http://pastebin.com/9q3iqk1W (If needed I can post it here also)

**Comment by mikepurvis** [comment]
Similar to roscpp's default configuration, all rosserial activity happens on a single thread— so if you block anywhere, either in your `loop()` function or in one of the callbacks, that will block all other activities (the callback come from inside `spinOnce()`). You have three seconds of delay in `callback` -> `setDriverTo`; you need to manage this timing using interrupts or `millis()` checks in your main loop.
