### ISSUE TITLE
Leak of file descriptions in /rosout

### ISSUE THREAD

**Issue by histfuture** [ros-drivers/rosserial#266]
When serial_node failed to open a serial port, `  client = SerialClient(port_name, baud) ` raise an exception, I found the serial_node is not closed correctly. 

By "lsof -p 'pid of rosout'", it shows an leaked file descriptor " can't identify protocol" . How to fix this problem?

**Comment by mikepurvis** [comment]
The relevant code is here:

https://github.com/ros-drivers/rosserial/blob/jade-devel/rosserial_server/src/serial_node.cpp

https://github.com/ros-drivers/rosserial/blob/jade-devel/rosserial_server/include/rosserial_server/serial_session.h

I would have expected the socket to be destructed when the `SerialSession` instance went out of scope, but maybe it's being held onto by something? I'd be delighted for you to dig into this.

**Comment by histfuture** [comment]
@mikepurvis  I use the python version and I found the problem is caused by the following code 
` rospy.signal_shutdown("Error opening serial: %s" % e) #in SerialClient.py line 351` and I test a simple code: 

` import rospy `
` if __name__=="__main__": `
`     rospy.init_node("serial_node") `
`     rospy.signal_shutdown("any reason") `

which also caused a leak of file descriptor, so I believe rospy.signal_shutdown is not an appropriate approach to "shut down" a ros node. But I did not know any correct approaches to stop a ros node by code,any idea?

**Comment by histfuture** [comment]
@mikepurvis 
Finally I found a tricky solution, just sleep for a second before  calling rospy.signal_shutdown and the problem disappeared.
