### ISSUE TITLE
where the rosserial_arduino lib source code?

### ISSUE THREAD

**Issue by dyan1024** [ros-drivers/rosserial#275]
when i test the example HelloWorld of rosserial_arduino fallow the tutorial on wiki http://wiki.ros.org/rosserial_arduino/Tutorials/Hello%20World 
recived something like
`\xff\xfe\x08\x00\xf7\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf5`

`\xff\xfeH\x00\xb7\x00\x00}\x00\x07\x00\x00\x00chatter\x0f\x00\x00\x00std_msgs/String \x00\x00\x00992ce8a1687cec8c8bd883ec73ca41d1\x00\x02\x00\x00#`

`\xff\xfe\x10\x00\xef}\x00\x0c\x00\x00\x00hello world!\xf9`
according to the rosserial_python code,the first looks like a response to heartbeat packet.
i'm look forward to view the lib source code in detail for how it work,but i cannot find the source code in where.

**Comment by mikepurvis** [comment]
It's all in here: https://github.com/ros-drivers/rosserial/tree/jade-devel/rosserial_client/src/ros_lib

Hope that helps.
