### ISSUE TITLE
What does __init__.py do? (empty file)

### ISSUE THREAD

**Issue by FirefoxMetzger** [ros-drivers/rosserial#276]
In

    rosserial/rosserial_client/src/rosserial_client/

there is an empty file called `__init__.py`. It was added 4 years ago and is a blank file. It doesn't seem to serve any purpose? Why does it exit?

**Comment by vmatos** [comment]
[Python modules](https://docs.python.org/2/tutorial/modules.html#packages)

This is not related with rosserial.

**Comment by sonyccd** [comment]
please close this issue
