### ISSUE TITLE
Twist.h, Quaternion.h is generated incorrectly by make_library.py

### ISSUE THREAD

**Issue by mikeferguson** [ros-drivers/rosserial#3]
In Twist.h, Vector3.h casts float \* to long \* then assigns it to int32_t*, which causes type mismatch in serialize(). Note: deserialize doesn't have the same problem. Problem must be in make_library.py. Result is Twist.h is unusable without manual modification.

The same problem exists in geometry_msgs/Point.h, geometry_msgs/TwistWithCovariance.h, and geometry_msgs/PoseWithCovariance.h

(copied from https://kforge.ros.org/rosserial/trac/ticket/76)

**Comment by mikeferguson** [comment]
As far as I can tell, this is not an issue in rosserial_arduino -- I assume we've found it to be an issue in rosserial_embedded?

@PaulBouchier could you elaborate on the problems you had? I assume you were on a system with _real_ 64-bit floats, in which case, we should also change to using those (the new changes support us varying which primitive is used on a particular platform)

**Comment by PaulBouchier** [comment]
This problem is undetected by the gcc-avr compiler apparently, but is picked up by the regular gcc compiler for arm. Below I've pasted a diff between the "original" i.e. as created by make_library.py message and a hand-edited version. It appears in quite a number of messages - I don't know all of them. You can see that in all cases, the original file cast a pointer to a long \* and tried to assign it to an int32_t *, which is a compilation error. The -orig.h files should be what you see generated from make_library.py (unless you fixed the bug).

Paul

bash-4.1$ cd geometry_msgs/
bash-4.1$ diff Vector3\ -\ Orig.h Vector3.h
22c22

## <       int32_t \* val_x = (long *) &(this->x);

> ```
>   int32_t * val_x = (int32_t *) &(this->x);
> ```
> 
> 36c36
> 
> ## <       int32_t \* val_y = (long *) &(this->y);
> 
> ```
>   int32_t * val_y = (int32_t *) &(this->y);
> ```
> 
> 50c50
> 
> ## <       int32_t \* val_z = (long *) &(this->z);
> 
> ```
>   int32_t * val_z = (int32_t *) &(this->z);
> ```
> 
> bash-4.1$ diff Point-Orig.h Point.h
> 22c22
> 
> ## <       int32_t \* val_x = (long *) &(this->x);
> 
> ```
>   int32_t * val_x = (int32_t *) &(this->x);
> ```
> 
> 36c36
> 
> ## <       int32_t \* val_y = (long *) &(this->y);
> 
> ```
>   int32_t * val_y = (int32_t *) &(this->y);
> ```
> 
> 50c50
> 
> ## <       int32_t \* val_z = (long *) &(this->z);
> 
> ```
>   int32_t * val_z = (int32_t *) &(this->z);
> ```
> 
> 112c112
> < #endif
> 
> ## \ No newline at end of file
> 
> #endif
> bash-4.1$ diff Quaternion-Orig.h Quaternion.h
> 23c23
> 
> ## <       int32_t \* val_x = (long *) &(this->x);
> 
> ```
>   int32_t * val_x = (int32_t *) &(this->x);
> ```
> 
> 37c37
> 
> ## <       int32_t \* val_y = (long *) &(this->y);
> 
> ```
>   int32_t * val_y = (int32_t *) &(this->y);
> ```
> 
> 51c51
> 
> ## <       int32_t \* val_z = (long *) &(this->z);
> 
> ```
>   int32_t * val_z = (int32_t *) &(this->z);
> ```
> 
> 65c65
> 
> ## <       int32_t \* val_w = (long *) &(this->w);
> 
> ```
>   int32_t * val_w = (int32_t *) &(this->w);
> ```
> 
> 138c138
> < #endif
> 
> ## \ No newline at end of file
> 
> #endif
> bash-4.1$ diff TwistWithCovariance-Orig.h TwistWithCovariance.h
> 25c25
> 
> ## <       int32_t \* val_covariancei = (long *) &(this->covariance[i]);
> 
> ```
>   int32_t * val_covariancei = (int32_t *) &(this->covariance[i]);
> ```
> 
> 70c70
> < #endif
> 
> ## \ No newline at end of file
> 
> #endif

**Comment by PaulBouchier** [comment]
I commented back to the list - it wasn't with real 64-bit floats. It
wouldn't let me attach an example generated file so I've attached it here.
Is there a way to attach a file to a github issue?

Paul

**Comment by mikeferguson** [comment]
OK, I see. This makes sense -- on AVR, long is int32_t since there is no int64_t. This one is an easy fix -- but we should also adjust the generator to use full float64s for your embedded_linux stuff.
