### ISSUE TITLE
make_library.py crashes on kobuki_testsuite message

### ISSUE THREAD

**Issue by PaulBouchier** [ros-drivers/rosserial#30]
To reproduce:
1. Install the turtlebot workstation packages as per the turtlbot wiki page:
$ sudo apt-get install ros-groovy-turtlebot ros-groovy-turtlebot-apps ros-groovy-turtlebot-viz 
This appears to install the kobuki base too.
1. Install & build rosserial
2. Install the arduino libraries into sketchbook/libraries. The install fails on the kobuki_testsuite ScanAngle message

Output of library install command:

bouchier@phb-netbook:~/sketchbook/libraries$ rosrun rosserial_arduino make_libraries.py .

Exporting to .
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
WARNING: Package name "swig-wx" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.
Exporting visualization_msgs
......
lots more libraries exported
......
Exporting kobuki_msgs

  Messages in: /opt/ros/groovy/share/kobuki_msgs
    CliffEvent, DigitalInputEvent, DockInfraRed, AutoDockingActionFeedback, Sound, DigitalOutput, AutoDockingResult, SensorState, RobotStateEvent, AutoDockingActionResult, AutoDockingGoal, AutoDockingActionGoal, PowerSystemEvent, KeyboardInput, AutoDockingAction, BumperEvent, WheelDropEvent, VersionInfo, ExternalPower, Led, AutoDockingFeedback, ButtonEvent, MotorPower, Exporting kobuki_testsuite

  Messages in: /opt/ros/groovy/share/kobuki_testsuite
    ScanAngle,
Traceback (most recent call last):
  File "/home/bouchier/catkin_ws/install/share/rosserial_arduino/make_libraries.py", line 90, in <module>
    rosserial_generate(rospack, path+"/ros_lib", ROS_TO_EMBEDDED_TYPES)
  File "/home/bouchier/catkin_ws/install/lib/python2.7/dist-packages/rosserial_client/make_library.py", line 560, in rosserial_generate
    MakeLibrary(p, path, rospack)
  File "/home/bouchier/catkin_ws/install/lib/python2.7/dist-packages/rosserial_client/make_library.py", line 495, in MakeLibrary
    md5sum = roslib.message.get_message_class(package+'/'+f[0:-4])._md5sum
AttributeError: 'NoneType' object has no attribute '_md5sum'
# 

Note the slight change I made in Messages line to output the path to the failing library.
It looks as if roslib.message.get_message_class is failing, but I can't see anything wrong with the format of the ScanAngle message, and diff shows it's the same as turtlebot_apps/turtlebot_calibration/msg/ScanAngle.msg

**Comment by mikeferguson** [comment]
I put a stupid hack in, since most people won't want kobuki_testsuite on rosserial. There are also some other messages that cause problems, so we should track these down later. I'll try to see what is going on over the next week or so, I'd like to kill all uses of roslib if possible.

**Comment by PaulBouchier** [comment]
Thanks Michael,

I didn't want kobuki_testsuite, & didn't even know I had any kobuki stuff.
It came along for the ride with something - I suspect with turtlebot debs
FYI. So this is just a comment that while I agree that most ppl won't want
kobuki_testsuite, if they're doing turtlebot, I suspect they'll get it
anyway. So it will be widespread.

I updated the build tutorial on the rosserial_arduino wiki page at
http://www.ros.org/wiki/rosserial_arduino/Tutorials/Arduino%20IDE%20Setup to
show what I believe are correct instructions for the source build and
ros_lib install sections for catkin & rosbuild. If you get a chance to look
at it, I'd welcome any corrections - I plan to change
rosserial_embeddedlinux the same way.

regards

Paul

**Comment by mikeferguson** [comment]
That wiki looks good. 

The kobuki_testsuite hack basically blacklists kobuki_testsuite messages from being exported. Not sure if there are any uses for that message, but I'm guessing people aren't really worried about the ScanAngle message.

**Comment by bit-pirate** [comment]
Accidentally came across this issue here. Is there any problem with the kobuki_testsuite message?

**Comment by mikeferguson** [comment]
As far as I can tell, there isn't anything wrong with these particular messages. I've blacklisted them currently, because I just haven't had time to really track down the real cause.

**Comment by mikeferguson** [comment]
I just opened a pull request against kobuki to fix this -- apparently your **init**.py loads drift_estimation which has a rospy call to a non-existent package name. We should add a more elegant failure mode for future packages that have issues, but this particular one is addressed.

**Comment by mikeferguson** [comment]
And I meant to include a link: https://github.com/yujinrobot/kobuki/pull/252

**Comment by mikeferguson** [comment]
https://github.com/ros-drivers/rosserial/pull/42 fixes the major issue (can't develop at all if you have a broken package/message on your system).
