### ISSUE TITLE
Array of Twists rosserial_windows

### ISSUE THREAD

**Issue by spencerh-b** [ros-drivers/rosserial#329]
I am trying to create a msg that looks as such

`std_msgs/Header header

geometry_msgs/Twist[] twists`

, but I'm unsure how to do this with rosserial_windows. I have it in a catkin_ws in linux bash, but do I need to make it again if I were to try and use the same msg in a visual studio's project? Just all around confused. Really anything helps.

**Comment by prnthp** [comment]
Yes, you need to run make_libraries.py every time you add new messages/services. And then use the resulting ros_lib. It should contain your new headers for the new messages.

**Comment by spencerh-b** [comment]
@prnthp thank you so much
