### ISSUE TITLE
Error in installation Debian 9 (Stretch) with ROS Lunar

### ISSUE THREAD

**Issue by sdan** [ros-drivers/rosserial#358]
I've been trying to install and it always get stuck at
`[ 95%] Building CXX object rosserial/rosserial_server/CMakeFiles/rosserial_server_serial_node.dir/src/serial_node.cpp.o
`
I created the catkin workspace by:
1. mkdir -p catkin-ws/src
2. catkin make
3. sourcing it
4. cloning this repo into src and then going back to catkin-ws to make it again

How should I go about this?

**Comment by TuxLeon** [comment]
Depending of your target you should go on with one of the links the Client Libraries chapter on this site.
http://wiki.ros.org/rosserial#Client_Libraries

**Comment by sdan** [comment]
Restarted task multiple times. Fixed the trivial issue.

**Comment by welkerCode** [comment]
@dantuluri I am having the same problem.  I get stuck at 95%, and am getting a lot of cpp output before the build fails.  Restarting catkin_make over and over eventually allows me to finish the build, but now I am getting an "ImportError: cannot import name Serial" every time I try to run rosrun rosserial_arduino /dev/ttyUSB0.   Did you have a similar problem?
