### ISSUE TITLE
C++ rosserial server

### ISSUE THREAD

**Issue by mikepurvis** [ros-drivers/rosserial#37]
Potentially a good idea, for a variety of reasons—performance for one, also support of roscpp-only features such as the unreliable transport.

One possible implementation strategy would be building a "lib" package which provides the guts of the server, and then a script which generates the user's specific rosserial_server_xxx package, possibly even by scanning the firmware source and/or package dependencies to automatically determine which messages are necessary to include in the binary.

**Comment by chuck-h** [comment]
I support this! I suspect the python rosserial driver is a bottleneck on Raspberry Pi. See http://wiki.jigsawrenaissance.org/ROS_on_RaspberryPi. Anything I can do to help?

**Comment by mikepurvis** [comment]
I've got a very early prototype of this knocked together—minimal robustness, but it supports publishing and subscribing over sockets, and would probably be suitable for use with embeddedlinux. For anyone interested to take a look or play along at home: https://github.com/mikepurvis/rosserial/tree/hydro-devel/rosserial_server

**Comment by PaulBouchier** [comment]
Closed by pull request #60
