### ISSUE TITLE
Arduino Zero (SAMD21) Native USB compiling Error

### ISSUE THREAD

**Issue by danielpcb3d** [ros-drivers/rosserial#376]
Dear all,

thanks for reading my issue.
I'm still working on a project based on a Arduino Zero like development Board (https://wiki.protoneer.co.nz/NANO-ARM) which should read values with his standard Serial1 Interface (Pin 0/1) and interact with ROS over his native USB port. 
I have written the Arduino Code and tested it with a 8bit uC and everything is working properly. Because the SAMD21 series has a native USB Port I have to add #define USE_USBCON  directly above #include <ros.h>to use the native USB Port to subscribe the values. If i try to compile the code I'm getting the following error: 
[...] ArduinoHardware.h:79:16: error: cannot convert 'Uart*' to 'Serial_*' in assignment
iostream = &Serial1;
I have written a few blog posts how to fix the problem, but changing iostream = &Serial1; into iostream = &Serial; didnt fixed my problem.

I'm using Arduino 1.8.5 IDE:
I would be very much appericate if someone could tell me what to do, to be able to use the Native USB port.
Thanks a lot.

**Comment by mikepurvis** [comment]
Please see https://github.com/ros-drivers/rosserial/issues/370#issuecomment-388936749 for the next steps on using ARM-based Arduinos.
