### ISSUE TITLE
Missed subscriptions

### ISSUE THREAD

**Issue by mikepurvis** [ros-drivers/rosserial#38]
We're having periodic issues where the MCU's request for a subscription fails to be processed by the rosserial serial node. It seems at present there is no mechanism in the protocol for an ack: setup is handled by a spew of TopicInfo messages, and ones with bit errors fall on the floor with a failed checksum.

My suggestion for how to change this would be to have a monitoring check in the firmware, which confirms that at least one message for each registered topic has been received, signalling a completed setup—if no message has been received, re-send the TopicInfo subscription command for that topic at some frequency, perhaps 1 Hz.

Similarly, in the server, the "Tried to publish before configured message" should probably trigger a re-sync attempt at some frequency, since that likely indicates a lost advertisement message.

**Comment by mikepurvis** [comment]
The issues continue to affect some of our products at Clearpath. I'm adding the fixes proposed above to my C++ implementation of rosserial_server.

**Comment by mikepurvis** [comment]
I ended up holding off on the proposed fixes, for two reasons:
- The logic is split: failed subscriptions must be detected in the client, whereas failed advertisements must be detected in the server.
- It increases complexity in the client.
- For occasional-use topics (like an estop trigger), there's a lot of chatter and repeated re-subscriptions.

A different proposal is to provide an optional "expect" parameter scheme with the server, so that the server can be started expecting to see certain advertisements and subscriptions from a connected client; if it doesn't seem them, then it can restart the connection until it does. This concentrates the robostness logic in the server, and makes it a fully optional, opt-in component.

**Comment by mikepurvis** [comment]
Any objections to an expect/require parameter for rosserial_server? We're using rosserial-connected MCUs in Kingfisher and Grizzly, and it's increasingly becoming unacceptable to have the possibility of a missed setup message. Suggested API would be:

```
  <node pkg="rosserial_server" type="serial_node" name="rosserial_server">
    <param name="port" value="$(arg port)" />
    <rosparam param="require">
      publishers: [ 'sense' ]
      subscribers: [ 'has_wifi', 'cmd_drive', 'estop' ]
    </rosparam>
  </node>
```

When an MCU connects, it has 1000ms to create the declared publishers and subscribers—if it fails to do so, rosserial_server shuts down the connection and starts over. This should not ever be necessary for socket-connected MCUs, since TCP is guaranteed delivery; it would be solely for serial-connected clients.

I've looked into a number of alternatives for guaranteeing setup, but all seem to require API changes (eg, to ack the setup messages) and/or significant increases in complexity on the server or client or both—the proposal above by comparison is straightforward, doesn't change the API, and lives entirely in the server.

A potential alternative would be to have this logic live outside the rosserial server _node_ in a separate monitoring node which checks to see that the appropriate topics are being advertised and subscribed-to by the server. If it doesn't like what it sees, it uses the rosnode Python API to kill off the server and let it respawn.

@PaulBouchier, @mikeferguson Thoughts on this stuff?

**Comment by PaulBouchier** [comment]
Hardening rosserial generally is a good thing. Rosserial is the most mature solution for connecting non-ros things to ROS, and I'm all over robustness improvements.

Not having thought much about the topic, still I like the expect/require approach in a launch script. Also, the server is the right place to put integrity-checking logic - it's closer to ROS and has much more capability for reporting/logging failures. If you feel like putting the logic into rosserial_python too I'd like that, but only if you have cycles to do it. 

Thinking about the big picture, ROS has challenges in the startup area generally, which need architecture to fix. This is a localized patch to address one element of a broader problem, but still, if it makes the system more robust in the short term it's a good thing, And it's general - it lets the system designer make assertions about how a part of the system should initialize, and have recovery actions triggered if it doesn't. 

I imagine you'll throw ROS warning or error messages if you have to restart the link. Also, the documentation on how to use the facility will be a good definition of the feature.

I like it. Thanks for your contributions Mike.
