### ISSUE TITLE
Python 3 vs Python 2.7

### ISSUE THREAD

**Issue by abarajithan11** [ros-drivers/rosserial#386]
I have python 3 installed via Anaconda on my Ubuntu computer. The package throws a lot of syntax errors since many files are written with python 2.7 I tried translating the package with 2to3 and then editing multiple files one by one and eliminated all syntax errors. Finally, the following error shows up when trying the Hello World code with arduino:

```
[INFO] [1533258022.518404]: Requesting topics...
[ERROR] [1533258037.520760]: Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino
```

I did the same on NVIDIA Jetson Tx2, which has only pyhton 2.7 and everything worked perfectly. Kindly give a solution to make this work with Anaconda-Python 3.

**Comment by mikepurvis** [comment]
Rosserial will be fully ported to Python 3 for the Noetic release.
