### ISSUE TITLE
Nothing in particular

### ISSUE THREAD

**Issue by craterghost** [ros-drivers/rosserial#391]

**Comment by romainreignier** [comment]
I have just tried to do the same on Ubuntu 18.04 with Arduino 1.8.6, AVR core 1.6.22 and latest rosserial code from git and I do not have such errors.
I have tried to compare your sketch and `ArduinoHardware.h` and it seems they are the same.
But please, format your code with Markdown to allow a better reading of the code snippets.
So I do not know what happen to you.
But note that this error:

> /home/julius/DFKI/Arduino/libraries/Rosserial_Arduino_Library/src/ArduinoHardware.h:42:33: error: expected ')' before '' token
> ArduinoHardware(SERIAL_CLASS io , long baud= 57600){

Looks suspicious. Like if you messed something up with macros or something that is included before ROS headers.
