### ISSUE TITLE
rosserial_arduino tutorial fails to reference code block

### ISSUE THREAD

**Issue by kejxu** [ros-drivers/rosserial#410]
[rosserial_arduino tutorial](http://wiki.ros.org/rosserial_arduino/Tutorials/Hello%20World) shows "Error: No code_block found" while explaining the code

**Comment by sevenbitbyte** [comment]
This is an ongoing issue on ROS wiki

You can track fix here -> https://github.com/ros-infrastructure/roswiki/issues/253

There is a similar report here -> https://discourse.ros.org/t/rosserial-arduino-tutorial-page-mistake/7449

**Comment by kejxu** [comment]
good to know! thanks for the update!
