### ISSUE TITLE
Why parity is not used for UART?

### ISSUE THREAD

**Issue by vyosypenko** [ros-drivers/rosserial#412]
Hi,
We try to make a connection between a MCU board and a PC as much reliable as possible. Parity in UART is dedicated to achieving this. 

So why parity is not used for UART in rosserial? 

Thanks,

**Comment by PetteriAimonen** [comment]
There is already a checksum in the packet, which will detect more errors than parity would. Parity bit in each byte would just decrease bandwidth by 10%, while not providing much extra reliability.

**Comment by mikepurvis** [comment]
Yup, and if you really want to, it's easy to turn it back on. But 8N1 is a pretty universal configuration for RS232 communication these days anyway.
