### ISSUE TITLE
ROS Melodic catkin_make fail

### ISSUE THREAD

**Issue by m090009** [ros-drivers/rosserial#419]
So my `catkin_make` fails with error
`AttributeError: 'module' object has no attribute 'Interpreter'`
As I searched for a solution I found that the problem is that there is a confusion between the `em` and the `empy` packages, so I proceeded to remove the `em` package as advised, but the error still persists.

**Comment by mikepurvis** [comment]
Feel free to reopen the ticket if you're still having this issue.
