### ISSUE TITLE
Weird behaviour when using arrays

### ISSUE THREAD

**Issue by bit-pirate** [ros-drivers/rosserial#45]
I want to publish readings of multiple sensors to the ROS world, hence I started using arrays (of ints). Unfortunately, I can't get them working properly.

Only a few entries are holding proper values. Here is an example output:

```
$ rostopic echo /rangers_data
layout: 
  dim: []
  data_offset: 0
data: [112, 112, 115, 80, 146, 164, 180, 125, 1665, 30, 1546]

---
layout: 
  dim: []
  data_offset: 0
data: [112, 87, 149, 71, 143, 159, 178, 125, 1665, 30, 1546]

---
layout: 
  dim: []
  data_offset: 0
data: [112, 88, 138, 74, 146, 166, 182, 125, 1665, 30, 1546]

---
layout: 
  dim: []
  data_offset: 0
data: [112, 106, 174, 64, 152, 164, 178, 125, 1665, 30, 1546]
```

The sensors (IR) are noisy, so the values should vary a bit, but only the values 2 - 7 are changing. 

Here some code:

```
  [...]
  std_msgs::Int16MultiArray rangers_msg;
  ros::Publisher pub_range( "rangers_data", &rangers_msg);
  [...]

void loop()
{
  now = millis();
  if ((now - last_rangers_time) > rangers_timing)
  {
    last_rangers_time = now;
    for (unsigned int ir = 0; ir < nr_of_irs; ++ir)
    {
      rangers_msg.data[ir] = analogRead(ir_pins[ir]);
//      rangers_msg.data[ir] = 123;
    }   
    pub_range.publish(&rangers_msg);
  }
  nh.spinOnce();
  [...]
}
```

If I change the array values from containing the analog reading to a fix value (e.g. 123), I get this:

```
$ rostopic echo /rangers_data
layout: 
  dim: []
  data_offset: 0
data: [112, 123, 123, 123, 123, 123, 123, 125, 1643, 30, 1546]

---
layout: 
  dim: []
  data_offset: 0
data: [112, 123, 123, 123, 123, 123, 123, 125, 1643, 30, 1546]

---
layout: 
  dim: []
  data_offset: 0
data: [112, 123, 123, 123, 123, 123, 123, 125, 1643, 30, 1546]

---
layout: 
  dim: []
  data_offset: 0
data: [112, 123, 123, 123, 123, 123, 123, 125, 1643, 30, 1546]
```

So, somehow the garbage gets added to the entries 1 and 8 - 11.
I can confirm my IRs are working, since I get proper readings when using Arduino-only code (publishing the values via the serial terminal).

Anyone has an idea what's going on?

**Comment by bit-pirate** [comment]
Btw, when I am using multiple variables - i.e. a message with range1, range2 etc. - everything works fine.

**Comment by mikeferguson** [comment]
So, with roscpp rangers_msg.data would be a std::vector, and you would have to do a resize() on it, before assigning these values. With rosserial, we have no std::vector, so rangers_msg.data is a raw pointer, there is no storage allocated yet.

You want to make some call to malloc(), or preferably (since malloc on micros is kinda prone to eventually failing), point data at some fixed size vector allocated elsewhere:

```
 int real_data_storage[10];
 range_msg.data = &real_data_storage;
 range_msg.data[0] = 123;
```

The array stuff is, regrettably, poorly documented.

**Comment by bit-pirate** [comment]
I thought this is done by setting the size of the array.

```
rangers_msg.ranges_length = nr_of_irs;
```

Would I need to do your instructions in addition to that?

**Comment by mikeferguson** [comment]
Yes. Setting the size of the array simply tells the "serialization" how much data to copy. It never actually allocates storage. When we originally designed the API, we had tried to avoid automatic allocation as much as possible, given the potentially huge sizes of messages and small memory sizes of the AVR.

**Comment by bit-pirate** [comment]
Puuuuh, that was it! You made my day! Please add this tip somewhere!
This weird behaviour (+ the string issue) kept me busy nearly the whole day! -.-
Maybe this is the solution to the string issue as well. I'll test that as soon I find some time.

PS: It didn't work for me when only passing the address, I had to do:

```
int range_storage[nr_of_irs];
[...]
rangers_msg.ranges = range_storage;
```
