### ISSUE TITLE
boost/asio/handler_type removed in boost 1.70

### ISSUE THREAD

**Issue by dodsonmg** [ros-drivers/rosserial#461]
I am building on FreeBSD.  The ports tree contains boost 1.72.  `boost/asio/handler_type` was removed in boost 1.70.  This causes `rosserial_server/udp_stream.h` to fail to build with a series of `no member named (get_service|get_implementation)`.

https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/reference/handler_type.html

**Comment by mikepurvis** [comment]
Fixed by #468.
