### ISSUE TITLE
rosserial_arduino cmake scripts

### ISSUE THREAD

**Issue by mitchellwills** [ros-drivers/rosserial#50]
The rosserial_arduino cmake scripts were removed in 60e534e9ea7bddee42d52ffc12f473bb25f1d716 and could be re-added. I don't know what implications catkin has for these scripts, but by using the scripts from the original arduino cmake repository (https://github.com/queezythegreat/arduino-cmake) they seem to work under groovy with rosbuild.

**Comment by mikepurvis** [comment]
My impression from @mikeferguson was that there wasn't really a great way to fit these in under catkin.

I'm wondering about the feasibility of a generator-type approach, where you have a one-liner which can create a new package ready-to-go with ros_lib, arduino headers, build and download targets all set up, etc. Having such a script, it might be nice to be able to specify the board at generation time, so any quirks with leonardo-vs-uno (etc) could be papered over at that point. (If it was sufficiently modular, such a rosserial_generator package could just indefinitely accept pull requests for generators targeting all manner of dev boards and toolchain setups.)

It's a tricky position that rosserial_arduino is in—not wanting to abandon users of the Arduino IDE, but ultimately supporting it largely for the sake of novices in the transition period before they dump it for cmake, a text editor, and a "real" ROS package.

**Comment by mikeferguson** [comment]
If someone has the time to debug and test it, it could certainly get merged in. I would recommend we not just copy the arduino-cmake project inside (as it then becomes out of date, as happened in the past).

As far as catkin goes, you're basically just outside the main catkin system anways (so is the Arduino IDE). What you're mainly using catkin for is deploying debs for the rosserial_python and rosserial_client stuff. In this case, I think anybody using the cmake stuff is probably installing from source (or at least, if we made that a requirement, it wouldn't be terrible for those users), and so you could install both rosserial and the arduino_cmake from source. This would probably reduce how many cmake scripts we end up having in the repo to maintain.

**Comment by mikepurvis** [comment]
Relevant discussion: https://github.com/ros/catkin/issues/484

**Comment by mikepurvis** [comment]
Okay, I have one of the internal CPR firmwares set up as a convenient catkin package, with targets for the firmware, upload, etc. It may be a while before I get around to extracting that as a generically usable thing, so if anyone's interested or wanting that, please contact me directly.

**Comment by getSurreal** [comment]
This issue appears to relate to an issue I'm having where there seems to be some missing files while trying to go through the rosserial_arduino CMake Tutorial http://wiki.ros.org/rosserial_arduino/Tutorials/CMake.  Is there a recommended workaround?

I'm running ROS Groovy on Raspberry PI Raspbian with Arduino 1.01

I posted more details here http://answers.ros.org/question/111336/rosserial_arduino-cmake-tutorial/

**Comment by mikepurvis** [comment]
The CMake builds have been reinstated, and are available in Indigo:

http://wiki.ros.org/rosserial_arduino/Tutorials/CMake
