### ISSUE TITLE
Teensy 4.0 usb serial broken on 20.04?

### ISSUE THREAD

**Issue by aatb-ch** [ros-drivers/rosserial#575]
I have tried setting up a Teensy 4.0 over usb serial and not getting any luck going through the USB serial connection. It works when going through the hardware Serial1 via a usbserial dongle. Seems to be a 20.04 usb issue, works on 18.04.

Wondered if anybody else has hit this problem? I've tried all the recommended steps, 00-rules, disabling modemmanager, no chance. Works completely fine with a Teensy LC on 20.04, same code, cables. With the T4.0 the serial connection hangs and must physically disconnect it.

It is not strictly a rosserial issue, but I hoped someone setting up the same config might have hit the same snag.

**Comment by warnerjon12** [comment]
I have used the Teensy 4.0 successfully with rosserial recently on 20.04. Don't think this is still an issue? Make sure you have your udev rules configured correctly.

**Comment by aatb-ch** [comment]
After much troubleshooting here https://forum.pjrc.com/threads/69166-Teensy-4-0-usb-serial-broken-on-Ubuntu-20-04?mode=hybrid the issue seems to be stemming from running 20.04 inside a VM environment (Parallels), so likely a usb emulation problem. I resorted to running on a non-VM machine and it all works fine.
