### ISSUE TITLE
rosserial_python tcp server doesn't work when forking

### ISSUE THREAD

**Issue by lorenzoriano** [ros-drivers/rosserial#67]
In file: SerialClient.py, function startSocketServer:

``` python
def startSocketServer(self, port, address):
    rospy.loginfo("starting ROS Serial Python Node serial_node-%r" % (address,))
    rospy.init_node("serial_node_%r" % (address,))
    self.startSerialClient()
```

the new init_node raises an exception:

```
ROSException: rospy.init_node() has already been called with different arguments: [...]
```

Basically forking is broken, but without forking the SerialClient can only handle one connection at a time.

**Comment by PaulBouchier** [comment]
Yes - I couldn't figure out how to make forking work properly in python. The documentation was very unclear as to whether it's a unix-style fork or more like a thread. If you provide a patch, I'll pull it in.

Paul

**Comment by mikepurvis** [comment]
@lorenzoriano If you're interested to check it out, my experimental C++ server handles many clients using boost::asio. For now it's in the [clearpath fork](https://github.com/clearpathrobotics/rosserial/tree/hydro-devel/rosserial_server), but Paul is working on merging it in.

Re another of your tickets, it also deregisters subscribers properly.

**Comment by zchen99** [comment]
Any update for fork_server feature? Thanks.
