### ISSUE TITLE
Can not deserialize the string type data correctly in the case of 8 bit architecture(e.g. ATMEGA2560)

### ISSUE THREAD

**Issue by tongtybj** [ros-drivers/rosserial#74]
Hi, I am testing the lastest rosserial version of hydro devel, using ATMEGA2560.
I suffer from the big problem that the topic message from arduino can not be deserialized correctly, mainly because of the wrong length of the string data.
The possible reason I think is that the change of <A Href="https://github.com/ros-drivers/rosserial/commit/522ab6e8afe46d8d15a9f0484bc6c0a7f65345f3">#61</A>.
I don't know whether the "32 bit architecture" indicates the micro processor of Arduino. If so, I expect a branch condition.
That is, remain the previous way of serialization/deserialization for the 8 bit architecture and add the new way fo serialization/deserialization for 32 bit architecture.

**Comment by PaulBouchier** [comment]
32-bit processor architecture indicates an ARM processor type, such as Arduino Due (i.e. not ATMEGA).

That change was supposed to be compatible with both ARM and Arduino, and I tested it with the simple Hello World publisher program. Please tell me what program you are testing it with, and what error you get. If it's broken I need to fix it.

**Comment by tongtybj** [comment]
I found that if there is only one publisher / subscriber in the program, such kind of problem would not occur.
However, when there are multiple publishers / subscribers in the program, the second and the subsequent publishers / subscribers can not be registered correctly because of the wrong length of string data.
<A Href="https://github.com/tongtybj/blank/blob/master/Test/Test.ino">This is the link of a simple sample which contains  two subscribers and two publishers.</A>

**Comment by PaulBouchier** [comment]
Thank you for the explanation of how to reproduce it. I'll look at it today.

**Comment by PaulBouchier** [comment]
Please see Issue 76 https://github.com/ros-drivers/rosserial/issues/76 for an explanation of the problem. It is fixed in the latest source, and I'll release new debs in the next couple of days. Please re-test to confirm the fix and re-open the issue if you still see a problem after updating to the latest version. Note: you will have to re-build ros_lib (rm -r ros_lib; rosrun rosserial_arduino make_libraries.py .) to get the fix.
