### ISSUE TITLE
rosserial_arduino: lib_ros affects behavior of servo control

### ISSUE THREAD

**Issue by dawonn** [ros-drivers/rosserial#79]
When I use rosserial to control a servo via the default tutorial example, the servo jitters sporadically. This behavior has not been noticed when running without lib_ros.

The servo is rather stable 99% of the time, but every so often it will jitter or bounce a few degrees for a split second only when lib_ros has been loaded in the sketch.

That this happens even after all publishers have been stopped, but the jitter is gone after serial_node.py has been shut down. 

I was under the impression that pin 9 on leonardo was a hardware PWM port and that servo.h would set up the PWM registers and leave them alone until a new angle was requested. Which would take cpu load out of the equation but I can't help but wonder if something in lib_ros is taking too long and causing the PWM to fail

I found that when the jitter happens, there is one PWM pulse which has a 7.9~8.2% duty cycle, whereas the normal pulses have a 7.5% duty cycle. So something is causing the chip to slow down and not get around to flipping the output by the deadline...  Any thoughts?

**Comment by dawonn** [comment]
Video of the PWM jitter: http://www.youtube.com/watch?v=u_PbfeG858Q

**Comment by mikeferguson** [comment]
Not sure  about the Leonardo, but as of Arduino 0016 or so, the main "Servo" library for Arduino switched from being true hardware PWM on two channels to be a software approach where one interrupt was used to generate up to 8 servo pulses. This software version does in fact glitch if you are really banging on the micro and using a lot of cyles in interrupts (thus delaying the servo interrupt). With ros_lib, you'll be getting lots of interrupts to handle the serial receive. You might look into to changing to a real hardware PWM servo library, as there are a couple of them out there (although I don't think any are installed by default).

**Comment by dawonn** [comment]
That's horrible.... why would they do such a thing!? 

Oh well, thank you for the info!

**Comment by dawonn** [comment]
For anyone else following my path of frustration: 

There are indeed libraries for hardware pwm control on there first gen ardino boards, the Leonardo has a differentdifferent cpu archecteure and thus they dont work. You will need to write your own interface. if I'm wrong please feel free to link to such a library for Leonardo. :-)
