### ISSUE TITLE
serial_node.py: more detailed exception error messages

### ISSUE THREAD

**Issue by dawonn** [ros-drivers/rosserial#81]
It would be awesome if there was an independent try/catch for each field in the deserialize routine, so that I can identify where the problem is more quickly.

**Comment by mikeferguson** [comment]
If I understand your request correctly, we can't really do that within rosserial -- the serialize/deserialize code is simply the standard ROS genpy-generated code -- any such fix would have to be in genpy.

**Comment by dawonn** [comment]
I see, fair enough.
