### ISSUE TITLE
IMU mesages don't work

### ISSUE THREAD

**Issue by dawonn** [ros-drivers/rosserial#84]
Continuing from:
http://answers.ros.org/question/91301/rosserial-fails-when-using-sensor_msgsimu/

I'm trying to publish a sensor_msgs::Imu topic from an arduino and while it appears to work (serial_node.py happily reports that it's publishing, and my LED's keep flashing appropriately), rostopic echo imu is totally quiet. 

I can publish all kinds of other topics including Header, Vector3, Int16Array, Quaterion, String, etc, and even the odom broadcaster example works. Sometimes I get an error about a buffer underfil from serial_node.py, but not always.

**Comment by dawonn** [comment]
The IMU message is overflowing the hardware serial port buffer, corrupting the message.

**Comment by tonybaltovski** [comment]
I found if you make a new message with no covariance it works fine.

**Comment by chrisspen** [comment]
How do you calculate the quaternion for the orientation field? My IMU gives me RPY, but it looks like `tf::createQuaternionMsgFromRollPitchYaw` isn't implemented in `rosserial_client/src/ros_lib/tf/tf.h`. Only `tf::createQuaternionFromYaw`, which isn't sufficient.

**Comment by mikepurvis** [comment]
Hi @chrisspen, you can populate a quaternion from RPY angles using the underlying definition, see:

https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles#Definition

**Comment by chrisspen** [comment]
Thanks, it's simpler to implement than I thought. However, since you didn't include that in rosserial, does that mean it's performance is so poor on the Arduino that I shouldn't waste my time trying to use it?

**Comment by chrisspen** [comment]
Yeah, I just tested it, and either the calculation's too much for the Uno, or the IMU packet (without covariance) I'm sending back is too big, but either way the Arduino becomes unresponsive.

**Comment by mikepurvis** [comment]
You could speed that up with a [lookup table](https://namoseley.wordpress.com/2015/07/26/sincos-generation-using-table-lookup-and-iterpolation/) if you wanted, but honestly if you're already passing some other message up to the PC, just pass your RPY values in a Vector3, and create the quaternion as part of expanding that into the standard Imu message.
