### ISSUE TITLE
TF messages are dissapearing

### ISSUE THREAD

**Issue by ibaranov-cp** [ros-drivers/rosserial#87]
Tf messages are received (rx led blinks on Arduino) but they fail to do anything. In the below code, the led on pin 13 does not blink. However, everything compiles and loads and connects through rosserial fine. Rostopic info shows that the server is subscribed to /tf

```
#include <ros.h>
#include <ros/time.h>
#include <std_msgs/Float32.h>
#include <tf2_msgs/TFMessage.h>

ros::NodeHandle  nh;


std_msgs::Float32 val;
ros::Publisher recv_val("rotation", &val);
geometry_msgs::TransformStamped t;


void messageCb( const tf2_msgs::TFMessage& tf_msg){
  digitalWrite(13, HIGH-digitalRead(13));   // blink the led
  t.transform.rotation.x = tf_msg.st_transforms.transform.rotation.x;
}

ros::Subscriber<tf2_msgs::TFMessage> sub("tf", messageCb );


void setup()
{
  nh.initNode();
  t.transform.rotation.x =0;
  nh.subscribe(sub);
  nh.advertise(recv_val);
}

void loop()
{ 
  val.data = t.transform.rotation.x;
  recv_val.publish(&val);
  nh.spinOnce();
  delay(100);
}
```

**Comment by mikepurvis** [comment]
It's an array of messages—check the [limitations related to arrays](http://wiki.ros.org/rosserial/Overview/Limitations). The implementation depends on realloc, which may be unavailable or failing. In any case, the `/tf` topic is a firehose of information which the uC probably does not need to care about 99% of.

My suggestion would be a proxy node which listens for the exact transform you care about, and publishes it to the uC on a dedicated topic as a sane messages format.
