### ISSUE TITLE
rosserial not syncing with Arduino Yun

### ISSUE THREAD

**Issue by bit-pirate** [ros-drivers/rosserial#91]
I'm currently trying to get my new [Arduino Yun](http://arduino.cc/en/Main/ArduinoBoardYun) publishing ROS messages, but the `serial_node` fails to sync.

```
$ rosrun rosserial_python serial_node.py /dev/ttyACM0
[INFO] [WallTime: 1387787958.202110] ROS Serial Python Node
[INFO] [WallTime: 1387787958.208201] Connecting to /dev/ttyACM0 at 57600 baud
[ERROR] [WallTime: 1387787975.315805] Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino
```

The same sketch (roslib's blink example) does work with my Arduino Uno.

Any ideas what the issue could be?

PS: I'm using the rosserial debs with version 0.5.4 with ROS Hydro on Ubuntu 12.04 64bit.

_Update:_
The Arduino Yun uses the ATmega32u4, the same micro controller used in the Arduino Leonardo. Users of the Leonardo seem to have similar problems, e.g.: http://answers.ros.org/question/61863/rosserial_python-cant-connect-to-arduino-leonardo/

**Comment by mikeferguson** [comment]
Have you tried a source install? I'm not sure how up-to-date our debs are -- further, we've definitely had weird problems with debs at times when moving to different platforms.

**Comment by bit-pirate** [comment]
The debs are actually quite up to date, but I just tested the source install as well. Unfortunately, I get the same results - working with the UNO, not working with the Yun.

Any more ideas?

**Comment by bit-pirate** [comment]
Ha! The comments in PR #78 caught my attention and so I tried it out and _it works_!

Please merge & re-release ASAP! :-)

**Comment by mikeferguson** [comment]
Cherry-picked, fixed in source.

**Comment by bit-pirate** [comment]
@mikeferguson thanks a lot!

**Comment by PaulBouchier** [comment]
Pushed a new debs release 0.5.5

**Comment by Gianluca67** [comment]
Hi Mike,

I'm working with an arduino mega 2560 and I've the problem

amministratore@Under-pressurE:~$ rosrun rosserial_python serial_node.py /dev/ttyACM0
[INFO] [WallTime: 1389805678.231300] ROS Serial Python Node
[INFO] [WallTime: 1389805678.240687] Connecting to /dev/ttyACM0 at 57600 baud
[ERROR] [WallTime: 1389805695.351360] Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino

My ubuntu is 12.04 LTS and I've ROS Hydro.
what I have to install again?

thanks
Gianluca

**Comment by PaulBouchier** [comment]
@Gianluca67 Please open a new issue for Arduino Mega 2560 and I'll try it when I get home in a couple of weeks. I can't think of any reason it shouldn't work if you're using the right serial port. Note that Arduino Mega has 4 serial ports and you'll have to use the first one, called Serial.

Paul

**Comment by JinglinZhang** [comment]
@Gianluca67 Hi, have you solve this problem? I met the same problem.

**Comment by whwqy** [comment]
hi I have the same problem.And I also don't know how to solve this problem .Have you solve this problem? Thank you

**Comment by whwqy** [comment]
@JinglinZhang   Hey  Jinglinzhang ,Have you solve this problem? I have the same problem.Could you tell me something about it?

**Comment by g0935260205** [comment]
I wrote some arduino yun example for streaming camera and using rosserial to exchange the data.
https://github.com/g0935260205/arduino-yun-with-ROS?fbclid=IwAR1VubduDDKUFAgxIKJM3207OIz28lpVCRuQ3nC5muvr71P8-i88XpSwuZ8

**Comment by tugrulzure** [comment]
> 

@PaulBouchier OMG I have spent weeks to get this to work using both usb ftdi and jetson tx serial port to mega. I never thought I could just use Serial and connect mega directly to jetson. Thanks so much! They should include this info in rosserial helloworld tutorial.
