### ISSUE TITLE
Abolition of rosserial for fuerte revision

### ISSUE THREAD

**Issue by tongtybj** [ros-drivers/rosserial#93]
I found that the repository for fuerte revision has been abolished recently(https://kforge.ros.org/rosserial/hg).
I understand that fuerte revision is out-of-date. But, there are couple of people use ros and rosserial based on fuerte revision. Is it possible to add backport for fuerte revision(e.g. fuerte branch)?

**Comment by mikeferguson** [comment]
I'm not sure we can accurately reconstruct what is released into Fuerte. We don't appear to have imported the tags/branches for earlier releases. I do notice https://github.com/ros-drivers/rosserial/commit/d9073fd1c9a97f74dae4044705a403574845f687 which claims to be a tag for Electric and version 0.3.0, which is about the closest thing we probably have. I don't see any other release numbers between that commit and the catkinization for Groovy.

I actually don't even recall how we used to release prior to catkin/bloom, but if somebody can determine that this "electric 0.3.0" tag was actually what we put into Fuerte, I can pretty much trivially point a fuerte-devel branch at it. (I suppose we should also point the wiki's electric/fuerte location to said branch).

**Comment by PaulBouchier** [comment]
I answered this same question privately the same way yesterday. My
recollection is we didn't release debs for Fuerte - the electric debs
worked fine. I was adding embeddedlinux source and you were catkinizing the
source for groovy during the Fuerte time, so I think electric source would
be what was available as debs during Fuerte.

Paul

**Comment by mikeferguson** [comment]
I've added a fuerte-devel branch, stopping at d9073fd1c9a97f74dae4044705a403574845f687

I think this is not exactly what was released into debs, but would have been the latest source at the time (debs appear to have been only 0.2.0, but we did prepare an 0.3.0 release, which I think initially only went into groovy before we released a catkinized version of 0.4.0)
