### ISSUE TITLE
Problem with make_library.py

### ISSUE THREAD

**Issue by 4lv4r0** [ros-drivers/rosserial#96]
Good afternoon 
I´m a member of ROS wiki community. We have found a problem with make_library.py (into rosserial_client) . Trying to generate a header file for a custom message. We run "rosrun rosserial_client make_library.py" and it seems like nothing happens. We have tested it in Groovy and Hydro. Here you can follow the issue if you want to check something: http://answers.ros.org/question/119031/rosserial_client-does-not-include-make_librarypy/?comment=129236#comment-129236. Could you take a look on it? Could you help me please? Thanks you so much

**Comment by mikeferguson** [comment]
The usage has changed signifigantly for the make_libraries within groovy/hydro and above (as a result of the catkinization). I've posted an answer to your question, and also updated the page on the wiki that you referenced.
